### ISSUE TITLE
ssl cert error

### ISSUE THREAD

**Issue by ghost** [rasata/Iphone-Powered#1]
- Hostname was NOT found in DNS cache
-   Trying 127.0.0.1...
- Connected to albert.apple.com (127.0.0.1) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSL connection using TLSv1.2 / AES256-GCM-SHA384
- Server certificate:
-        subject: C=US; ST=Some-State; O=Apple Inc.; OU=Apple iPhone; CN=Apple iPhone Activation
-        start date: 2014-08-15 22:19:23 GMT
-        expire date: 2041-12-31 22:19:23 GMT
- SSL: certificate subject name 'Apple iPhone Activation' does not match target host name 'albert.apple.com'
- Closing connection 0
  (null)
  Failed to send request or retrieve response.

**Comment by rasata** [comment]
Sorry for this late answer :-)
So how did you solve the problem ?
