### ISSUE TITLE
INSTALLATION

### ISSUE THREAD

**Issue by Derewith** [rasata/Iphone-Powered#2]
How to install correctly iphone-powered 

( not only git clone on cmd but if anyone can teach me how to do all the things to set up it correctly )

**Comment by dekepetz** [comment]
yeah... please give an tutorial to install it step by step

**Comment by drmatrix** [comment]
Si vous pouvez poster un petit tuto ou guide d'utilisation , le node js est nouveau pour la plupart des developpeurs , on vous remerci de tout coeur de votre grand efforts

**Comment by BladiMar** [comment]
yeah, a tutorial on how 2 install will be awesome :) thanks in advance.
