### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by leonpapke** [rasata/Iphone-Powered#3]
hello, 

after i've received the information from itunes, how can i decrypt them ?
someone has an idea ?

**Comment by drmatrix** [comment]
you still have reference to this folder 
/Users/rasata/.nvm/v0.10.24/lib/node_modules/sails/node_modules/
how can u make it dynamic ?

**Comment by leonpapke** [comment]
i started with node 2 days ago :D dont know what you mean with dynamic
