### ISSUE TITLE
Hi brother

### ISSUE THREAD

**Issue by achoe** [rasata/Iphone-Powered#4]
Please help me when i can make it bypassed iTunes after run sails lift and get back any info of device back to my PC. But i was very bad so can't going continue to done. I know any right step it will be done with full function. 
I think modify info back to PC from iTunes then send back to iTunes will help it done. But important i can't send back to iTunes that info. 
Can u help me? Please!

**Comment by leonpapke** [comment]
if i know how to do this, i would help you. but i also dont have any idea about what to do next. itunes is bypassed but i cant get any informations with this.

**Comment by achoe** [comment]
iTunes bypassed mean "bypass without ID iCloud" and its showed Setup as new iPhone

**Comment by leonpapke** [comment]
yes. but that doesnt help me to get any information about the previous owner

**Comment by achoe** [comment]
i got back info activation. I thought can modify it then send back to iTunes. But i didn't know how to send back info to iTunes

**Comment by leonpapke** [comment]
me neither :/ but please tell me when you found a way
