### ISSUE TITLE
iphone

### ISSUE THREAD

**Issue by victorrent1** [rasata/Iphone-Powered#6]

**Comment by TWoinONe1** [comment]
Hi . icloud bypass olny bypass itunes, not iphone.. or I do some wrong ?

**Comment by rasata** [comment]
Yes it only bypass itunes

**Comment by iamcaps** [comment]
hi there rasata , can you leave me your email please ?!

**Comment by alfonso78** [comment]
That's my email , who are you?

Alfonso
Inviato da iPhone

**Comment by iamcaps** [comment]
hi there im a nodejs user , saw what you have developed with the nodejs bypass , can you help me to develop it  to a higher level ? to continue the work like exploring files and so on ? thanks alot
Best regards ,
Bogdan 

```
 On Tuesday, January 6, 2015 7:02 PM, alfonso78 <notifications@github.com> wrote:
```

That's my email , who are you?

Alfonso
Inviato da iPhone
