### ISSUE TITLE
wireshark does not see anything on the loopback interface

### ISSUE THREAD

**Issue by alex-kewl** [rasata/Iphone-Powered#8]
ca va, Rasata,

nice implementation of mdm (I guess)
this is not really an issue, but rather rfc, but "c" is not "comments" - in this case, "c" is for clarifications... )
in your description you are saying that all data will be captured, but I do not see any interface to see captured data or search it (like you are saying there).

Also, what's weird, your app supposed to listen on the loopback interface on port 443, but wireshark does not see anything, and itunes won't do anything unless there's a working connection to Internet...  Do you have a brief description of data flow - which connections/transactions take place during this whole "bypassing"? Or may be you've seen a good diagram on the Internet. 

I don't need to bypass activation or whatever - just playing around.

**Comment by rasata** [comment]
yop :-) 
To clarify it,  the way all "doulci" services act is just by answering a static html when itunes is trying to activate an iphone,
So when itunes try to use : 

```
https://alber.apple.com//deviceservices/deviceActivation
```

it answer something like this : 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.apple.com/itms/" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="iTunes Store" />
    <meta name="description" content="iTunes Store" />
    <title>iPhone Activation</title>
    <link href="http://static.ips.apple.com/ipa_itunes/stylesheets/shared/common-min.css" charset="utf-8" rel="stylesheet" />
    <link href="null/deviceservices/stylesheets/styles.css" charset="utf-8" rel="stylesheet" />
    <link href="http://static.ips.apple.com/ipa_itunes/stylesheets/pages/IPAJingleEndPointErrorPage-min.css" charset="utf-8" rel="stylesheet" />
    <script id="protocol" type="text/x-apple-plist"><plist version="1.0">
  <dict>
    <key>iphone-activation</key>
    <dict>
      <key>ack-received</key>
      <true/>
      <key>show-settings</key>
      <true/>
    </dict>
  </dict>
</plist></script>
    <script>
        var protocolElement = document.getElementById("protocol");
        var protocolContent = protocolElement.innerText;iTunes.addProtocol(protocolContent);
    </script>
</head>
<body>
</body>
</html><br><b>  GadgetWide Unknown Error Accrued for  ! Move to WTF Mode and Get Default Apple Response.</b><br>

```

I don't know if this answer to your question, but anyway, I hold the development of this tool as I discover that [http://www.libimobiledevice.org/](Lib Imobile Device) is doing the job of analyzing any mobile apple device.

Hope this will help you :-)

**Comment by alex-kewl** [comment]
merci)

thanks for clarifying a typical "doulci" transaction.

Still not sure, why no traffic is passing the loopback interface. I will look into that a bit later. Yeah, you provided plenty of information to fill my evenings for a couple weeks :-)
Thanks, anyways! )
